name: Sync

on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  index:
    name: Sync projects between Todoist and Notion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run index
        env:
          TODOIST_TOKEN: ${{secrets.TODOIST_TOKEN}}
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          TOGGL_TOKEN: ${{secrets.TOGGL_TOKEN}}
        run: |
          npm ci
          npm run sync
