name: TNbridge

on:
  push:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  TNbridge:
    name: Sync projects between Todoist and Notion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run TNbridge
        env:
          TODOIST_TOKEN: ${{secrets.TODOIST_TOKEN}}
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
        run: |
          yarn
          yarn TNbridge